#!/bin/bash
set -e

SUBSCRIPTION_DISPLAY_NAME=${1}
KEY_VAULT=${2}
USERNAME=${3}
PASSWORD=${4}
PRIVATE_KEY_PATH=${5}
RECOVERY_TOKENS_PATH=${6}

function usage() {
  echo "usage: ./set-github-secrets <subscription-display-name> <key_vault> <username> <password> <private_key_path> <recovery_tokens_path>"
}

if [ -z "${SUBSCRIPTION_DISPLAY_NAME}" ] || [ -z "${KEY_VAULT}" ] || [ -z "${USERNAME}" ] || [ -z "${PASSWORD}" ] || [ -z "${PRIVATE_KEY_PATH}" ] || [ -z "${RECOVERY_TOKENS_PATH}" ] ; then
  usage
  exit 1
fi

function keyvault_secret_set() {
  local SECRET=${1}
  local VALUE=${2}
  az keyvault secret set --vault-name ${KEY_VAULT} --name ${SECRET} --value ${VALUE} --subscription ${SUBSCRIPTION_DISPLAY_NAME} 
}

function keyvault_file_set() {
  local SECRET=${1}
  local FILE_PATH=${2}
  az keyvault secret set --vault-name ${KEY_VAULT} --name ${SECRET} --file ${FILE_PATH} --subscription ${SUBSCRIPTION_DISPLAY_NAME} 
}

keyvault_secret_set flux-github-username "${USERNAME}"
keyvault_secret_set flux-github-password "${PASSWORD}"
keyvault_file_set flux-github-private-key "${PRIVATE_KEY_PATH}"
keyvault_file_set flux-github-recovery-tokens "${RECOVERY_TOKENS_PATH}"

